spring:
  application:
    name: OnlineFlashcards
  datasource:
    password: ${MYSQL_PASSWORD}
    url: jdbc:mariadb://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: never
      continue-on-error: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
logging:
  level:
    org.springframework.boot.context.config: DEBUG
    org.springframework.jdbc.datasource: DEBUG