spring:
  application:
    name: OnlineFlashcards
  datasource:
    password: password
    url: "jdbc:mariadb://127.0.0.1:3307/flashcards"
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect